### ISSUE TITLE
[Bug]: Overwritten translations

### ISSUE THREAD

**Issue by forxer** [Laravel-Lang/common#172]
### Lang Package Name

laravel-lang/publisher

### Lang Package Version

all versions

### Laravel Framework Version

all versions

### PHP Version

all versions

### Issue description

Hello @andrey-helldar,

We have already discussed this problem in [Overloaded translation #329](https://github.com/Laravel-Lang/publisher/issues/329)

This same problem now occurs in the same way in your official plugins.

For example in the “Action” plugin there is the “image” key. This is, in the plugin, translated into English as [“Image”](https://github.com/Laravel-Lang/actions/blob/6755fb7dfabd66f29a55a9e644700642e148762d/source/actions.json#L50C15-L50C20). 

But it is overwritten by the ["image" validation key](https://github.com/Laravel-Lang/lang/blob/fc74a734fe361fbc75b0463885634a6ef9a7cbcf/source/framework/10.x/validation.php#L67).

This is a problem that will appear more and more.

### Steps to reproduce

You have already reproduced in [Overloaded translation #329](https://github.com/Laravel-Lang/publisher/issues/329)

**Comment by andrey-helldar** [comment]
Added isolation of plug-ins. You don't need to do anything extra - publisher under the hood will use this mechanism and stop going to other plugins for translations even if they are defined in the same package. The list of plugins is added to the main `Plugin` file in each package. For example: https://github.com/Laravel-Lang/lang/blob/main/src/Plugin.php#L15-L48

[The fix is released](https://github.com/Laravel-Lang/publisher/releases/tag/16.2.2). Thanks!
