### ISSUE TITLE
I hope to customize the locale and item_id fields

### ISSUE THREAD

**Issue by hteen** [Laravel-Lang/common#207]
### Feature description

When using ```$video->getTranslation("title")``` to get the title, the final SQL generated is:
```sql
select * from `video_translations` where `locale` in (zh_CN, en) and `video_translations`.`item_id` in (1)
```
Reading the source code, I found that ```locale``` and ```item_id``` cannot be customized

**Comment by andrey-helldar** [comment]
The `item_id` really can't be customizable, as it's not necessary. This field is rigidly bound to a specific record of the main table and has a mapping to the `locale` field, which together are included in a composite unique index.

The `locale` field also cannot be customized because it belongs to a specific localization.

The query includes the condition `where `locale` in (zh_CN, en)` because your application is requesting a Chinese localization and, in case a translation is not available, it will get an English translation. The `models.filter.enabled` parameter of the [config/localization.php](https://github.com/Laravel-Lang/config/blob/main/config/public.php#L164) config file is responsible for this filtering. If you turn it off, the query will return all created localizations.

Also, if you need to get a translation for a localization other than main or fallback, pass the localization as the second argument to the `getTranslation` method in one of the ways. For example:

```php
use LaravelLang\LocaleList\Locale;

$video->getTranslation('title', 'fr');
$video->getTranslation('title', Locale::French);
```

**Comment by andrey-helldar** [comment]
And why do you want to customize the values of these fields?
